### ISSUE TITLE
AttributeError: 'RandomSurvivalForest' object has no attribute 'criterion'

### ISSUE THREAD

**Issue by quanghieu31** [sebp/scikit-survival#512]
I checked my `X_train` and `y_train` are all in correct format but keep getting this error when running `rsf.fit(X_train, y_train)`
```
File sklearn\base.py:480, in _validate_data(self, *args, **kwargs)
      [0](file:///sklearn/base.py:0) <Error retrieving source code with stack_data see ipython/ipython#13598>
...
--> [719](file:///sklearn/ensemble/_forest.py:719)     # missing values
    [720](file:///sklearn/ensemble/_forest.py:720)     estimator = type(self.estimator)(criterion=self.criterion)
    [721](file:///sklearn/ensemble/_forest.py:721)     return {"allow_nan": _safe_tags(estimator, key="allow_nan")}

AttributeError: 'RandomSurvivalForest' object has no attribute 'criterion'
```

I also checked that there is no `np.nan` in my data. Could it possibly a bug or my misunderstanding?

Thank you.

**Comment by sebp** [comment]
Can you please paste the output of

```python
import sksurv; sksurv.show_versions()
```

**Comment by Sebge** [comment]
I stumbled upon the same problem. I think it's connected with the newer scikit-learn version and their support for missing values in ensembles. An upgrade to scikit-surv 0.23.1 actually needs me to downgrade to scikit-learn 1.4.2, but surprisingly, the following environment did not abort at installation time:
```
>>> sksurv.show_versions()
SYSTEM
------
Platform          : Linux-6.8.0-52-generic-x86_64-with-glibc2.35
Python version    : CPython <module 'platform' from '/home/...../lib/python3.12/platform.py'>
Python interpreter: /home/..../bin/python

DEPENDENCIES
------------
scikit-survival   : 0.23.0
scikit-learn      : 1.6.1
numpy             : 1.26.4
scipy             : 1.13.1
pandas            : 2.2.2
numexpr           : 2.10.1
ecos              : 2.0.14
osqp              : 0.6.7.post3
joblib            : 1.4.2
matplotlib        : 3.9.4
pytest            : 8.3.4
sphinx            : None
Cython            : None
pip               : 24.0
setuptools        : 71.0.4
``` 
MWE:

```
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sksurv.datasets import load_breast_cancer
from sksurv.ensemble import RandomSurvivalForest
from sksurv.util import Surv

x, y = load_breast_cancer()
times = y["t.tdm"]
censoring = y["e.tdm"]

x_train, x_test, times_train, times_test, censoring_train, censoring_test = train_test_split(x, times, censoring, random_state=10)#, stratify=statification)
rsf = RandomSurvivalForest(random_state=10, max_depth=6, n_estimators=200)

rsf.fit(x_train, Surv.from_arrays(censoring_train, times_train))
y_pred = rsf.predict(x_test)

```
leading to 

```
sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
Traceback (most recent call last):
  File "mwe.py", line 15, in <module>
    rsf.fit(x_train, Surv.from_arrays(censoring_train, times_train))
  File "/sksurv/ensemble/forest.py", line 107, in fit
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csc", ensure_min_samples=2, force_all_finite=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sklearn/base.py", line 480, in _validate_data
    return validate_data(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sklearn/utils/validation.py", line 2920, in validate_data
    tags = get_tags(_estimator)
           ^^^^^^^^^^^^^^^^^^^^
  File "/sklearn/utils/_tags.py", line 430, in get_tags
    sklearn_tags_provider[klass] = klass.__sklearn_tags__(estimator)  # type: ignore[attr-defined]
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sklearn/ensemble/_forest.py", line 719, in __sklearn_tags__
    estimator = type(self.estimator)(criterion=self.criterion)
                                               ^^^^^^^^^^^^^^
AttributeError: 'RandomSurvivalForest' object has no attribute 'criterion'
```

**Comment by sebp** [comment]
sksurv 0.23.0 doesn't work with scikit-learn 1.6. Currently, only git 
version in git supports it.

Did you install sksurv via pip, or conda?

**Comment by sebp** [comment]
Version 0.24.0 has been released which adds support for scikit-learn. Therefore, I'm closing this issue. If the issue persists with the latest version, please leave a comment.
